"""
Feasibility crawl: reconstruct npm dependency-slot allocation over time.

Constraint (verified): registry.npmjs.org is the only reachable source.
There is no reverse-dependency-lookup API anywhere on the allowed network
(api.deps.dev, npms.io, packages.ecosyste.ms, www.npmjs.com/browse/depended
all 403 at the proxy). So "who depends on axios" cannot be queried directly.

Design: build a broad, category-agnostic candidate pool of popular npm
packages (via generic search terms unrelated to the category under test),
then for each candidate fetch its ABBREVIATED registry doc (dependencies
per version, no publish times, ~10-40x smaller than the full doc) and
check whether any version's dependencies include a member of the category
set. Only for packages that qualify do we pay for the FULL doc (which
carries the top-level "time" map) to get real dates.

This is a real crawl, not a simulation: nothing about which packages
exist, what they depend on, or when, is generated by us.
"""
import json
import time
import urllib.request
import urllib.error
import os

CACHE_DIR = os.path.join(os.path.dirname(__file__), "cache")
os.makedirs(CACHE_DIR, exist_ok=True)

UA = {"User-Agent": "orgenrgy-research-crawl/0.1 (feasibility test, contact via github.com/ekeane-rawhide/orgenrgy)"}

def _get(url, headers=None, retries=3, timeout=20):
    h = dict(UA)
    if headers:
        h.update(headers)
    req = urllib.request.Request(url, headers=h)
    for attempt in range(retries):
        try:
            with urllib.request.urlopen(req, timeout=timeout) as resp:
                return resp.read()
        except urllib.error.HTTPError as e:
            if e.code == 404:
                return None
            if attempt == retries - 1:
                raise
            time.sleep(1.5 * (attempt + 1))
        except Exception:
            if attempt == retries - 1:
                raise
            time.sleep(1.5 * (attempt + 1))
    return None

def cache_path(kind, name):
    safe = name.replace("/", "__")
    return os.path.join(CACHE_DIR, f"{kind}__{safe}.json")

import urllib.parse

def search_raw(text, size=250):
    cp = cache_path("search", f"{text}_{size}")
    if os.path.exists(cp):
        return json.load(open(cp))
    url = f"https://registry.npmjs.org/-/v1/search?text={urllib.parse.quote(text)}&size={size}"
    data = _get(url)
    obj = json.loads(data) if data else {"objects": []}
    json.dump(obj, open(cp, "w"))
    time.sleep(0.15)
    return obj

def abbrev_doc(pkg):
    cp = cache_path("abbrev", pkg)
    if os.path.exists(cp):
        return json.load(open(cp))
    url = f"https://registry.npmjs.org/{urllib.parse.quote(pkg, safe='@/')}"
    data = _get(url, headers={"Accept": "application/vnd.npm.install-v1+json"})
    obj = json.loads(data) if data else None
    json.dump(obj, open(cp, "w"))
    time.sleep(0.1)
    return obj

def full_doc(pkg):
    cp = cache_path("full", pkg)
    if os.path.exists(cp):
        return json.load(open(cp))
    url = f"https://registry.npmjs.org/{urllib.parse.quote(pkg, safe='@/')}"
    data = _get(url)
    obj = json.loads(data) if data else None
    json.dump(obj, open(cp, "w"))
    time.sleep(0.15)
    return obj
